#The initial number of connections that are created when the pool is started. 
initialSize=100
#100\u5e76\u53d1
maxActive=100
#The maximum number of active connections that can be allocated from this pool at the same time, or negative for no limit.
maxTotal=1000
#The maximum number of connections that can remain idle in the pool, without extra ones being released, or negative for no limit.
maxIdle=100
maxWait=60000
#The minimum number of connections that can remain idle in the pool, without extra ones being created, or zero to create none.
minIdle=10
